/*DROP TABLE IF EXISTS Users;*/
CREATE TABLE IF NOT EXISTS Users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userName TEXT NOT NULL
);

/*DROP TABLE IF EXISTS Restaurants;*/
CREATE TABLE IF NOT EXISTS Restaurants (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userID INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    restName TEXT NOT NULL,
    FOREIGN KEY(userID) REFERENCES Users(id)
);

/*DROP TABLE IF EXISTS FoodCategories;*/
CREATE TABLE IF NOT EXISTS FoodCategories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    restID INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    categoryName TEXT NOT NULL,
    FOREIGN KEY(restID) REFERENCES Restaurants(id)
);

/*DROP TABLE IF EXISTS FoodSubCategories;*/
CREATE TABLE IF NOT EXISTS FoodSubCategories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    categoryID INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subCategoryName TEXT NOT NULL,
    FOREIGN KEY(categoryID) REFERENCES FoodCategories(id)
);

/*DROP TABLE IF EXISTS Dishes;*/
CREATE TABLE IF NOT EXISTS Dishes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    restID INTEGER,
    categoryID INTEGER,
    subCategoryID INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dishName TEXT NOT NULL,
    dishDescription TEXT,
    dishPrice INTEGER,
    FOREIGN KEY(restID) REFERENCES Restaurants(id),
    FOREIGN KEY(categoryID) REFERENCES FoodCategories(id),
    FOREIGN KEY(subCategoryID) REFERENCES FoodSubCategories(id)
);

/*DROP TABLE IF EXISTS DishPictures;*/
CREATE TABLE IF NOT EXISTS DishPictures (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dishID INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    picPath TEXT NOT NULL,
    FOREIGN KEY(dishID) REFERENCES Dishes(id)
);